openapi: 3.0.3

VisitReservationDetailRequest:
  title: 출입예약 Request
  type: object
  properties:
    id:
      type: integer
      example: 4
    name:
      type: string
      example: Arthur Dent
    details:
      type: string
      example: details
  # Both properties are required
  required:
    - id
    - name
VisitReservationDetailResponse:
  title: 출입예약 Response
  type: object
  properties:
    id:
      type: integer
      example: 4
    name:
      type: string
      example: Arthur Dent
    result:
      type: string
      example: Arthur Dent
    details:
      type: string
      example: details
  # Both properties are required
  required:
    - id
    - name