openapi: 3.0.3

VisitReservationListRequest:
  title: 출입예약 Request
  type: object
  properties:
    id:
      type: integer
      example: 4
    name:
      type: string
      example: Arthur Dent
    lists:
      type: string
      example: lists
  # Both properties are required
  required:
    - id
    - name
VisitReservationListResponse:
  title: 출입예약 Response
  type: object
  properties:
    id:
      type: integer
      example: 4
    name:
      type: string
      example: Arthur Dent
    result:
      type: string
      example: Arthur Dent
    lists:
      type: string
      example: lists
  # Both properties are required
  required:
    - id
    - name